name: Production Deploy

on:
  push:
    branches:
      - 'production'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    name: Deploy to ECR and Sync Tag
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      APP_NAME: ${{ secrets.APP_NAME }}
      ENV_SUFFIX: production
      ECR_REPO: ${{ secrets.APP_NAME }}-${{ env.ENV_SUFFIX }}-repo
      INFRA_REPO: TP1-OuterMSA/msa-infra-main
      SERVICE_PATH: charts/services/${{ secrets.APP_NAME }}

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Short Commit SHA
        id: sha
        run: echo "TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$TAG .
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$TAG

      - name: Clone Infra Repo and Update Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${INFRA_REPO}.git
          cd msa-infra-main

          yq e -i ".image.tag = \"$TAG\"" $SERVICE_PATH/values.yaml

          git add $SERVICE_PATH/values.yaml
          git commit -m "chore($APP_NAME): 이미지 태그 $TAG로 업데이트"
          git push origin main
