name: Production Deploy

on:
  push:
    branches:
      - 'production'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ECR and Sync Tag
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.CD_AWS_REGION }}
      APP_NAME: ${{ secrets.CD_APP_NAME }}
      INFRA_REPO: TP1-OuterMSA/msa-infra-main
      SERVICE_PATH: charts/services/${{ secrets.CD_APP_NAME }}

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Dynamic Environment Variables
        run: |
          echo "TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "ECR_REPO=${{ secrets.CD_APP_NAME }}-production-repo" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$TAG .
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$TAG
          

      - name: Clone Infra Repo and Update Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.CD_GH_PAT }}@github.com/${{ env.INFRA_REPO }}.git
          cd msa-infra-main

          yq e -i ".image.tag = \"$TAG\"" $SERVICE_PATH/values.yaml

          git add $SERVICE_PATH/values.yaml
          git commit -m "chore($APP_NAME): 이미지 태그 $TAG로 업데이트"
          git push origin main
